<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(AppTargetFramework)</TargetFramework>
    <AssemblyTitle>MagicPictureSetDownloader.Interface</AssemblyTitle>
    <Product>MagicPictureSetDownloader.Interface</Product>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Common.Log" />
  </ItemGroup>
</Project>