<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <AssemblyTitle>Common.ViewModel</AssemblyTitle>
    <Product>Common.ViewModel</Product>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common.Library\Common.Library.csproj" />
    <ProjectReference Include="..\Common.Notify\Common.Notify.csproj" />
  </ItemGroup>
</Project>