<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net6.0-windows;net7.0-windows;net8.0-windows;net9.0-windows</TargetFrameworks>
    <AssemblyTitle>Common.ViewModel</AssemblyTitle>
    <Product>Common.ViewModel</Product>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common.Collection\Common.Collection.csproj" />
    <ProjectReference Include="..\Common.Library\Common.Library.csproj" />
    <ProjectReference Include="..\Common.Notify\Common.Notify.csproj" />
    <ProjectReference Include="..\Common.Threading\Common.Threading.csproj" />
  </ItemGroup>
</Project>