<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0-windows;net9.0-windows</TargetFrameworks>
    <AssemblyTitle>Common.WPF.Converter.UnitTests</AssemblyTitle>
    <Product>Common.WPF.Converter.UnitTests</Product>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Common.WPF.Converter\Common.WPF.Converter.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>
  <ItemGroup>
    <None Update="ImageSample.bmp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>