<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net6.0;net7.0;net8.0;net9.0</TargetFrameworks>
    <AssemblyTitle>Common.Database</AssemblyTitle>
    <Product>Common.Database</Product>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common.Enums\Common.Enums.csproj" />
    <ProjectReference Include="..\Common.Library\Common.Library.csproj" />
  </ItemGroup>
</Project>