<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <AssemblyTitle>Common.Enums.UnitTests</AssemblyTitle>
    <Product>Common.Enums.UnitTests</Product>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Common.Enums\Common.Enums.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>
</Project>