<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(AppTargetFramework)-windows</TargetFramework>
    <AssemblyTitle>MagicPictureSetDownloader.DbGenerator</AssemblyTitle>
    <Product>MagicPictureSetDownloader.DbGenerator</Product>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup>
    <EmbeddedResource Include="MagicDataScryFall.zip" />
    <EmbeddedResource Include="MagicPicture.zip" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Common.SQLite" />
    <PackageReference Include="Common.Zip" />
  </ItemGroup>
</Project>