<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <AssemblyTitle>Common.Zip</AssemblyTitle>
    <Product>Common.Zip</Product>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SharpZipLib" />
  </ItemGroup>
</Project>