<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <AssemblyTitle>Common.Web</AssemblyTitle>
    <Product>Common.Web</Product>
    <AssemblyVersion>1.1.0</AssemblyVersion>
    <Version>1.1.0</Version>
    <FileVersion>1.1.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Net.Http" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common.Notify\Common.Notify.csproj" />
    <ProjectReference Include="..\Common.Threading\Common.Threading.csproj" />
  </ItemGroup>
</Project>