<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net6.0;net7.0;net8.0;net9.0</TargetFrameworks>
    <AssemblyTitle>Common.Collection</AssemblyTitle>
    <Product>Common.Collection</Product>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common.Library\Common.Library.csproj" />
    <ProjectReference Include="..\Common.Threading\Common.Threading.csproj" />
  </ItemGroup>
</Project>